### ISSUE TITLE
每日一题

### ISSUE THREAD

**Issue by quibbler01** [huashanqitu/labuladong-python3#1]
先来一道：

> 很多个key值，可能重复，请按照个数从多到少的形式排序输出key，格式：key-count。

**Comment by quibbler01** [comment]
> 先来一道：
> 
> > 很多个key值，可能重复，请按照个数从多到少的形式排序输出key，格式：key-count。

提示，堆排序

**Comment by huashanqitu** [comment]
背八股文都没时间呢，别闹。close
